name: free_book
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  appflowy_editor: ^6.1.0 # 编辑器
  adaptive_theme: ^3.7.2 # 主题切换
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1 # 状态管理
  fluttertoast: ^9.0.0
  path_provider: # 应用路径提供.鸿蒙移植版
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  flutter_floating_bottom_bar: ^1.3.0
  animated_notch_bottom_bar: ^1.0.3

dependency_overrides:
  # fluttertoast: # 系统级toast提示.鸿蒙移植版
  #   git:
  #     url: https://gitcode.com/openharmony-sig/flutter_fluttertoast.git
  #     ref: br_fluttertoast_v8.2.11_ohos
  # file_picker_ohos: # 文件选择器.鸿蒙移植版
  #   git:
  #     url: https://gitcode.com/openharmony-sig/fluttertpc_file_picker.git
  #     path: ohos
  file_selector: # 文件选择器.鸿蒙移植版
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/file_selector/file_selector
      ref: br_file_selector-v1.0.3_ohos
  url_launcher: # appflowy_editor用到.鸿蒙移植版
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/url_launcher/url_launcher
      ref: br_url_launcher_v6.3.1_ohos
  shared_preferences: # 缓存.鸿蒙移植版
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.5.3_ohos"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
